language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
  case_sensitive: false
  use_word_boundaries: true

- name: LexicalSyntacticFeaturizer

- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4


- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
  entity_recognition: true

- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true

- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

regex_features:
- name: wo_ref_no
  pattern: "[A-Za-z0-9\\-_]+"
- name: project_id
  pattern: "\\d+"
- name: date
  pattern: "\\d{4}-\\d{2}-\\d{2}"

lookup_tables:
- name: city
  elements:
  - Dubai
  - Abu Dhabi
  - Sharjah
  - Al Ain

policies:
- name: RulePolicy
- name: TEDPolicy
assistant_id: 20250724-132326-impulsive-fluid
